spring.application.name=backend

# Conexión con MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/mindalive
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Conexión con MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=mindalive_mongo
gemini.api.key=AIzaSyDmpCEOvUqra9PSBkPGHHkOJoFXGhwXA3k